export default {
	goku: require('../../assets/goku.png'),
	vegeta: require('../../assets/vegeta.png'),
	gohan: require('../../assets/gohan.png'),
	trunks: require('../../assets/trunks.png'),
	frieza: require('../../assets/frieza.png'),
	cell: require('../../assets/cell.png'),
	buu: require('../../assets/buu.png'),
	beerus: require('../../assets/beerus.png'),
	piccolo: require('../../assets/piccolo.png'),
	gotenks: require('../../assets/gotenks.png'),
	hit: require('../../assets/hit.png'),
	krillin: require('../../assets/krillin.png'),
	jiren: require('../../assets/jiren.png'),
	tien: require('../../assets/tien.png'),
	'android 17': require('../../assets/android17.png'),
	'android 18': require('../../assets/android18.png'),
	broly: require('../../assets/broly.png'),
	vegito: require('../../assets/vegito.png'),
	gogeta: require('../../assets/gogeta.png'),
	'goku black': require('../../assets/gokublack.png'),
};
